-- Pautas iniciais ficam como rascunho para revisão factual e inclusão de imagens autorizadas.
-- Substitua ADMIN_UUID pelo UUID do administrador antes de executar.
insert into public.posts(title,slug,excerpt,content,cover_alt,category,tags,status,source_url,created_by) values
('Academia Ocidentalense de Letras fortalece a cultura e a memória local','academia-ocidentalense-de-letras-fortalece-a-cultura-e-a-memoria-local','Uma pauta sobre cultura, memória e valorização das raízes de Cidade Ocidental.','## Em revisão editorial\n\nEsta pauta foi criada a partir da publicação pública indicada como referência. O texto final deve ser conferido pela equipe do mandato antes da publicação.','Academia Ocidentalense de Letras','Cultura e turismo',array['cultura','memória'],'draft','https://www.instagram.com/sanchespaivago/reel/DUReMXSjRWA/','ADMIN_UUID'),
('Valorização da bandeira e do brasão de Cidade Ocidental','valorizacao-da-bandeira-e-do-brasao-de-cidade-ocidental','A identidade do município e a importância de preservar seus símbolos oficiais.','## Em revisão editorial\n\nPauta preparada para apuração e validação pela equipe antes de ser publicada.','Bandeira e brasão de Cidade Ocidental','Projetos e leis',array['identidade','história'],'draft','https://www.instagram.com/reel/DZGGFPnh41I/','ADMIN_UUID'),
('Casa do Artesão impulsiona o artesanato e a economia criativa','casa-do-artesao-impulsiona-o-artesanato-e-a-economia-criativa','Espaço para abordar o artesanato local e a economia criativa.','## Em revisão editorial\n\nConfirmar informações, contexto e imagem autorizada antes da publicação.','Artesanato de Cidade Ocidental','Desenvolvimento econômico',array['artesanato','economia criativa'],'draft','https://www.instagram.com/sanchespaivago/reel/Ckrd0JbjBNE/','ADMIN_UUID'),
('Ações e oportunidades voltadas aos jovens da cidade','acoes-e-oportunidades-voltadas-aos-jovens-da-cidade','Pauta editorial dedicada à juventude e à construção de oportunidades.','## Em revisão editorial\n\nConteúdo aguardando validação factual da equipe.','Jovens de Cidade Ocidental','Juventude e oportunidades',array['juventude','oportunidades'],'draft','https://www.instagram.com/reel/DF_Wx9POH6k/','ADMIN_UUID'),
('Conquistas que estão marcando o mandato','conquistas-que-estao-marcando-o-mandato','Prestação de contas sobre ações e conquistas do mandato.','## Em revisão editorial\n\nDetalhar apenas realizações confirmadas pela documentação oficial.','Prestação de contas do mandato','Mandato em ação',array['mandato','prestação de contas'],'draft','https://www.instagram.com/p/DaQ02grFVp2/','ADMIN_UUID'),
('Parcerias que fortalecem a atuação parlamentar','parcerias-que-fortalecem-a-atuacao-parlamentar','Uma pauta sobre diálogo institucional e trabalho conjunto.','## Em revisão editorial\n\nIdentificar e confirmar as parcerias antes de publicar.','Atuação parlamentar de Sanches Paiva','Mandato em ação',array['parcerias','mandato'],'draft','https://www.instagram.com/reel/DHrbQGBuKJO/','ADMIN_UUID'),
('Desenvolvimento econômico também começa apoiando quem empreende','desenvolvimento-economico-tambem-comeca-apoiando-quem-empreende','Empreendedorismo local como pauta do desenvolvimento econômico.','## Em revisão editorial\n\nValidar os detalhes da visita e as informações dos participantes.','Visita a empreendedor local','Desenvolvimento econômico',array['empreendedorismo','economia'],'draft','https://www.instagram.com/p/C8KWqRHO__2/','ADMIN_UUID'),
('Comunidade, fé e presença nos momentos importantes da cidade','comunidade-fe-e-presenca-nos-momentos-importantes-da-cidade','Uma pauta para registrar a presença comunitária com respeito e contexto.','## Em revisão editorial\n\nIncluir apenas eventos e informações confirmados pela equipe.','Encontro comunitário em Cidade Ocidental','Comunidade e fé',array['comunidade','fé'],'draft',null,'ADMIN_UUID');
