(async()=>{
  const message=(text,error=false)=>{const el=document.querySelector('.admin-message');if(el){el.textContent=text;el.style.color=error?'#ffaaa5':'#ffd56b'}};
  const login=document.querySelector('#login-form');
  if(login){try{await APP.api('/api/auth/session');location.replace('/admin');return}catch{}login.addEventListener('submit',async e=>{e.preventDefault();message('Verificando acesso…');const fd=new FormData(login);try{await APP.api('/api/auth/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});location.replace('/admin')}catch(error){message(error.message,true)}});return}
  try{await APP.api('/api/auth/session')}catch{location.replace('/admin/login');return}
  document.querySelector('#logout')?.addEventListener('click',async()=>{await APP.api('/api/auth/logout',{method:'POST'});location.replace('/admin/login')});
  const table=document.querySelector('#posts-table');
  if(table){let posts=[];const search=document.querySelector('#admin-search'),filter=document.querySelector('#admin-filter');function draw(){const term=search.value.toLowerCase(),state=filter.value,shown=posts.filter(p=>(state==='all'||p.status===state)&&`${p.title} ${p.category}`.toLowerCase().includes(term));table.innerHTML=shown.length?shown.map(p=>`<article class="post-row"><div><h2>${APP.escape(p.title)}</h2><p>${APP.escape(p.category)} · ${APP.formatDate(p.published_at||p.created_at)}${p.featured?' · Destaque':''}</p></div><span class="status-pill ${p.status}">${p.status==='published'?'Publicado':'Rascunho'}</span><div class="row-actions"><a href="/admin/noticias/${p.id}/editar">Editar</a>${p.status==='published'?`<a href="/blog/${APP.escape(p.slug)}" target="_blank">Ver ↗</a>`:''}<button type="button" data-toggle="${p.id}" data-status="${p.status}">${p.status==='published'?'Despublicar':'Publicar'}</button></div></article>`).join(''):'<p>Nenhuma notícia encontrada.</p>';table.setAttribute('aria-busy','false')}try{posts=await APP.api('/api/posts');document.querySelector('#stats').innerHTML=`<div class="stat"><strong>${posts.length}</strong>Total</div><div class="stat"><strong>${posts.filter(p=>p.status==='published').length}</strong>Publicadas</div><div class="stat"><strong>${posts.filter(p=>p.status==='draft').length}</strong>Rascunhos</div>`;draw()}catch(e){message(e.message,true)}search.addEventListener('input',draw);filter.addEventListener('change',draw);table.addEventListener('click',async e=>{const b=e.target.closest('[data-toggle]');if(!b)return;b.disabled=true;const next=b.dataset.status==='published'?'draft':'published';try{const updated=await APP.api(`/api/posts/${b.dataset.toggle}/status`,{method:'PATCH',body:JSON.stringify({status:next})});Object.assign(posts.find(p=>p.id===updated.id),updated);draw();message(next==='published'?'Notícia publicada.':'Notícia retirada do site.')}catch(error){message(error.message,true);b.disabled=false}});return}
  const form=document.querySelector('#post-form');if(!form)return;form.elements.category.innerHTML=APP.categories.map(c=>`<option>${APP.escape(c)}</option>`).join('');const match=location.pathname.match(/noticias\/([^/]+)\/editar/),id=match?.[1],deleteButton=document.querySelector('#delete-post');let gallery=[];
  if(id){document.querySelector('#editor-title').textContent='Editar notícia';deleteButton.hidden=false;try{const p=await APP.api(`/api/posts/${id}`);for(const key of ['title','slug','excerpt','content','cover_url','cover_alt','category','status','source_url','seo_title','seo_description'])if(form.elements[key])form.elements[key].value=p[key]||'';form.elements.tags.value=(p.tags||[]).join(', ');form.elements.featured.checked=p.featured;form.elements.published_at.value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):'';gallery=p.gallery||[]}catch(e){message(e.message,true);form.hidden=true;return}}
  form.elements.title.addEventListener('input',()=>{if(!id||!form.elements.slug.dataset.edited)form.elements.slug.value=APP.slug(form.elements.title.value)});form.elements.slug.addEventListener('input',()=>{form.elements.slug.dataset.edited='1';form.elements.slug.value=APP.slug(form.elements.slug.value)});
  const validImage=file=>['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)&&file.size<=8*1024*1024;async function upload(files){if(files.some(f=>!validImage(f)))throw new Error('Use JPEG, PNG, WebP ou AVIF com no máximo 8 MB.');const body=new FormData();files.forEach(file=>body.append('images',file));return(await APP.api('/api/uploads',{method:'POST',body})).urls}
  form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;message('Salvando…');try{const fd=new FormData(form),cover=document.querySelector('#cover-file').files[0],files=[...document.querySelector('#gallery-files').files];if(cover)fd.set('cover_url',(await upload([cover]))[0]);if(files.length)gallery.push(...(await upload(files)).map(url=>({url,alt:fd.get('title')})));const status=fd.get('status'),payload={title:fd.get('title').trim(),slug:APP.slug(fd.get('slug')),excerpt:fd.get('excerpt').trim(),content:fd.get('content').trim(),cover_url:fd.get('cover_url')||null,cover_alt:fd.get('cover_alt').trim(),category:fd.get('category'),tags:fd.get('tags').split(',').map(v=>v.trim()).filter(Boolean),gallery,status,featured:fd.get('featured')==='on',source_url:fd.get('source_url')||null,seo_title:fd.get('seo_title')||null,seo_description:fd.get('seo_description')||null,published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():(status==='published'?new Date().toISOString():null)};await APP.api(id?`/api/posts/${id}`:'/api/posts',{method:id?'PUT':'POST',body:JSON.stringify(payload)});message('Notícia salva com sucesso.');setTimeout(()=>location.replace('/admin'),500)}catch(error){message(error.message,true);button.disabled=false}});
  deleteButton.addEventListener('click',async()=>{if(!confirm('Excluir esta notícia permanentemente?'))return;try{await APP.api(`/api/posts/${id}`,{method:'DELETE'});location.replace('/admin')}catch(e){message(e.message,true)}});const dialog=document.querySelector('#preview-dialog');document.querySelector('#preview-button').addEventListener('click',()=>{document.querySelector('#preview-content').innerHTML=`<p class="eyebrow">${APP.escape(form.elements.category.value)}</p><h1>${APP.escape(form.elements.title.value||'Título da notícia')}</h1><p>${APP.escape(form.elements.excerpt.value)}</p>${APP.renderMarkdown(form.elements.content.value)}`;dialog.showModal()});dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close())
})();
