(async()=>{
  const message=(text,error=false)=>{const el=document.querySelector('.admin-message');if(el){el.textContent=text;el.style.color=error?'#ffaaa5':'#ffd56b'}};
  if(!APP.configured){message('Configure o Supabase em data.js antes de usar o painel.',true);return}
  const {data:{session}}=await APP.db.auth.getSession();
  const login=document.querySelector('#login-form');
  if(login){if(session){location.replace('/admin');return}login.addEventListener('submit',async e=>{e.preventDefault();message('Verificando acesso…');const values=new FormData(login);const {error}=await APP.db.auth.signInWithPassword({email:values.get('email'),password:values.get('password')});if(error){message('E-mail ou senha inválidos.',true);return}const {data:allowed}=await APP.db.rpc('is_admin');if(!allowed){await APP.db.auth.signOut();message('Esta conta não possui permissão administrativa.',true);return}location.replace('/admin')});return}
  if(document.querySelector('[data-protected]')){if(!session){location.replace('/admin/login');return}const {data:allowed,error}=await APP.db.rpc('is_admin');if(error||!allowed){await APP.db.auth.signOut();location.replace('/admin/login');return}}
  document.querySelector('#logout')?.addEventListener('click',async()=>{await APP.db.auth.signOut();location.replace('/admin/login')});
  const table=document.querySelector('#posts-table');
  if(table){let posts=[];const search=document.querySelector('#admin-search'),filter=document.querySelector('#admin-filter');function draw(){const term=search.value.toLowerCase(),state=filter.value;const shown=posts.filter(p=>(state==='all'||p.status===state)&&`${p.title} ${p.category}`.toLowerCase().includes(term));table.innerHTML=shown.length?shown.map(p=>`<article class="post-row"><div><h2>${APP.escape(p.title)}</h2><p>${APP.escape(p.category)} · ${APP.formatDate(p.published_at||p.created_at)}${p.featured?' · Destaque':''}</p></div><span class="status-pill ${p.status}">${p.status==='published'?'Publicado':'Rascunho'}</span><div class="row-actions"><a href="/admin/noticias/${p.id}/editar">Editar</a>${p.status==='published'?`<a href="/blog/${APP.escape(p.slug)}" target="_blank">Ver ↗</a>`:''}<button type="button" data-toggle="${p.id}" data-status="${p.status}">${p.status==='published'?'Despublicar':'Publicar'}</button></div></article>`).join(''):'<p>Nenhuma notícia encontrada.</p>';table.setAttribute('aria-busy','false')}const {data,error}=await APP.db.from('posts').select('*').order('created_at',{ascending:false});if(error){message('Não foi possível carregar as notícias.',true)}else{posts=data||[];document.querySelector('#stats').innerHTML=`<div class="stat"><strong>${posts.length}</strong>Total</div><div class="stat"><strong>${posts.filter(p=>p.status==='published').length}</strong>Publicadas</div><div class="stat"><strong>${posts.filter(p=>p.status==='draft').length}</strong>Rascunhos</div>`;draw()}search.addEventListener('input',draw);filter.addEventListener('change',draw);table.addEventListener('click',async e=>{const b=e.target.closest('[data-toggle]');if(!b)return;b.disabled=true;const next=b.dataset.status==='published'?'draft':'published';const changes={status:next};if(next==='published')changes.published_at=new Date().toISOString();const {error}=await APP.db.from('posts').update(changes).eq('id',b.dataset.toggle);if(error){message('Não foi possível alterar a publicação.',true);b.disabled=false;return}const post=posts.find(p=>p.id===b.dataset.toggle);Object.assign(post,changes);draw();message(next==='published'?'Notícia publicada.':'Notícia retirada do site.')});return}
  const form=document.querySelector('#post-form'); if(!form)return;
  const categories=form.elements.category;categories.innerHTML=APP.categories.map(c=>`<option>${APP.escape(c)}</option>`).join('');
  const match=location.pathname.match(/noticias\/([^/]+)\/editar/),id=match?.[1],deleteButton=document.querySelector('#delete-post');let gallery=[];
  if(id){document.querySelector('#editor-title').textContent='Editar notícia';deleteButton.hidden=false;const {data:p,error}=await APP.db.from('posts').select('*').eq('id',id).single();if(error||!p){message('Notícia não encontrada.',true);form.hidden=true;return}for(const key of ['title','slug','excerpt','content','cover_url','cover_alt','category','status','source_url','seo_title','seo_description'])if(form.elements[key])form.elements[key].value=p[key]||'';form.elements.tags.value=(p.tags||[]).join(', ');form.elements.featured.checked=p.featured;form.elements.published_at.value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):'';gallery=p.gallery||[]}
  form.elements.title.addEventListener('input',()=>{if(!id||!form.elements.slug.dataset.edited)form.elements.slug.value=APP.slug(form.elements.title.value)});form.elements.slug.addEventListener('input',()=>{form.elements.slug.dataset.edited='1';form.elements.slug.value=APP.slug(form.elements.slug.value)});
  const validImage=file=>['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)&&file.size<=8*1024*1024;
  async function upload(file,folder){if(!validImage(file))throw new Error('Use JPEG, PNG, WebP ou AVIF com no máximo 8 MB.');const ext=file.name.split('.').pop().toLowerCase();const path=`${session.user.id}/${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await APP.db.storage.from('post-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return APP.db.storage.from('post-images').getPublicUrl(path).data.publicUrl}
  form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;message('Salvando…');try{const fd=new FormData(form),cover=document.querySelector('#cover-file').files[0],files=[...document.querySelector('#gallery-files').files];if(cover)fd.set('cover_url',await upload(cover,'covers'));for(const file of files)gallery.push({url:await upload(file,'gallery'),alt:fd.get('title')});const status=fd.get('status');const payload={title:fd.get('title').trim(),slug:APP.slug(fd.get('slug')),excerpt:fd.get('excerpt').trim(),content:fd.get('content').trim(),cover_url:fd.get('cover_url')||null,cover_alt:fd.get('cover_alt').trim(),category:fd.get('category'),tags:fd.get('tags').split(',').map(v=>v.trim()).filter(Boolean),gallery,status,featured:fd.get('featured')==='on',source_url:fd.get('source_url')||null,seo_title:fd.get('seo_title')||null,seo_description:fd.get('seo_description')||null,published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():(status==='published'?new Date().toISOString():null)};let query=id?APP.db.from('posts').update(payload).eq('id',id):APP.db.from('posts').insert({...payload,created_by:session.user.id});const {error}=await query;if(error){if(error.code==='23505')throw new Error('Este slug já está em uso. Escolha outro.');throw error}message('Notícia salva com sucesso.');setTimeout(()=>location.replace('/admin'),700)}catch(error){message(error.message||'Não foi possível salvar.',true);button.disabled=false}});
  deleteButton.addEventListener('click',async()=>{if(!confirm('Excluir esta notícia permanentemente? Esta ação não pode ser desfeita.'))return;const {error}=await APP.db.from('posts').delete().eq('id',id);if(error){message('Não foi possível excluir.',true);return}location.replace('/admin')});
  const dialog=document.querySelector('#preview-dialog');document.querySelector('#preview-button').addEventListener('click',()=>{document.querySelector('#preview-content').innerHTML=`<p class="eyebrow">${APP.escape(form.elements.category.value)}</p><h1>${APP.escape(form.elements.title.value||'Título da notícia')}</h1><p>${APP.escape(form.elements.excerpt.value)}</p>${APP.renderMarkdown(form.elements.content.value)}`;dialog.showModal()});dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
})();
