(()=>{document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/blog-fixes.css">');document.querySelector('[data-mode="saved"]')?.remove();
  const feed=document.querySelector('#post-feed');if(!feed)return;
  const ui={status:document.querySelector('#feed-status'),search:document.querySelector('#post-search'),filters:document.querySelector('#category-filters'),more:document.querySelector('#load-more'),count:document.querySelector('#post-count'),trending:document.querySelector('#trending-list'),toast:document.querySelector('#blog-toast'),nav:document.querySelector('.feed-nav-card')};
  const categories=[['Todos','✦',null],['Mandato','◎','Mandato em ação'],['Projetos e leis','▤','Projetos e leis'],['Obras e melhorias','⌂','Obras e melhorias'],['Desenvolvimento','↗','Desenvolvimento econômico'],['Cultura e turismo','◇','Cultura e turismo'],['Comunidade','◉','Comunidade e fé'],['Juventude','☆','Juventude e oportunidades'],['Agenda','□','Agenda']];
  let posts=[],visible=5,category=null,mode='feed';
  const saved=()=>{try{return JSON.parse(localStorage.getItem('sanches-saved-posts')||'[]')}catch{return[]}};
  const save=list=>localStorage.setItem('sanches-saved-posts',JSON.stringify(list));
  const notify=text=>{ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>ui.toast.classList.remove('show'),2600)};
  function filtered(){const term=ui.search.value.trim().toLocaleLowerCase('pt-BR'),ids=saved();let list=posts.filter(p=>(!category||p.category===category)&&(!term||[p.title,p.excerpt,p.content,p.category,...(p.tags||[])].join(' ').toLocaleLowerCase('pt-BR').includes(term)));if(mode==='saved')list=list.filter(p=>ids.includes(p.id));if(mode==='popular')list.sort((a,b)=>(b.views_count||0)-(a.views_count||0)||(new Date(b.published_at)-new Date(a.published_at)));else list.sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));return list}
  const card=p=>{const isSaved=saved().includes(p.id),minutes=p.reading_time||APP.readingTime(p.content),url=`post.html?slug=${encodeURIComponent(p.slug)}`;return `<article class="post-card reveal visible" data-id="${p.id}"><header class="post-author"><span class="author-mark">SP</span><div><strong>Sanches Paiva <i class="verified" aria-label="Conteúdo oficial">✓</i></strong><span>Conteúdo oficial</span></div><span class="post-category">${APP.escape(p.category)}</span></header><a class="post-cover" href="${url}"><img src="${APP.escape(p.cover_url||APP.fallbackImage)}" alt="${APP.escape(p.cover_alt||p.title)}" loading="lazy" onerror="this.src='${APP.fallbackImage}'"></a><div class="post-actions"><button type="button" data-share="${APP.escape(p.slug)}" aria-label="Compartilhar ${APP.escape(p.title)}"><span>↗</span> Compartilhar</button><button type="button" class="${isSaved?'saved':''}" data-save="${p.id}" aria-pressed="${isSaved}" aria-label="${isSaved?'Remover dos salvos':'Salvar notícia'}"><span>${isSaved?'▣':'▱'}</span> ${isSaved?'Salva':'Salvar'}</button><span class="read-time">◷ ${minutes} min de leitura</span></div><div class="post-card-body"><h2><a href="${url}">${APP.escape(p.title)}</a></h2><p>${APP.escape(p.excerpt)}</p><a href="${url}">Ler notícia completa →</a></div></article>`};
  function draw(){const list=filtered(),shown=list.slice(0,visible);feed.innerHTML=shown.map(card).join('');feed.setAttribute('aria-busy','false');ui.count.textContent=`${list.length} ${list.length===1?'publicação':'publicações'}`;ui.status.textContent=list.length?'':mode==='saved'?'Você ainda não salvou nenhuma notícia.':'Nenhuma notícia encontrada. Tente outro termo ou categoria.';ui.more.hidden=list.length<=visible;ui.more.disabled=false;ui.more.textContent='Carregar mais publicações'}
  function drawCategories(){ui.filters.innerHTML=categories.map(([label,icon,value])=>`<button type="button" class="${category===value?'active':''}" data-category="${APP.escape(value||'')}" aria-pressed="${category===value}"><span class="category-icon" aria-hidden="true">${icon}</span><span>${label}</span></button>`).join('')}
  function drawTrending(){const list=[...posts].sort((a,b)=>(b.views_count||0)-(a.views_count||0)||(new Date(b.published_at)-new Date(a.published_at))).slice(0,3);ui.trending.innerHTML=list.length?list.map((p,i)=>`<a class="trend-item" href="post.html?slug=${encodeURIComponent(p.slug)}"><span class="trend-number">${String(i+1).padStart(2,'0')}</span><img src="${APP.escape(p.cover_url||APP.fallbackImage)}" alt="" loading="lazy"><div><h3>${APP.escape(p.title)}</h3><time datetime="${APP.escape(p.published_at)}">${APP.formatDate(p.published_at)}</time></div></a>`).join(''):'<p class="feed-status">Sem dados de acesso ainda.</p>'}
  ui.filters.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;category=b.dataset.category||null;visible=5;drawCategories();draw();b.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})});
  document.querySelector('.category-arrow.previous').addEventListener('click',()=>ui.filters.scrollBy({left:-300,behavior:'smooth'}));document.querySelector('.category-arrow.next').addEventListener('click',()=>ui.filters.scrollBy({left:300,behavior:'smooth'}));
  ui.search.addEventListener('input',()=>{visible=5;draw()});ui.nav.addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;mode=b.dataset.mode;visible=5;ui.nav.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('active',item===b));draw()});
  ui.more.addEventListener('click',()=>{ui.more.disabled=true;ui.more.textContent='Carregando…';setTimeout(()=>{visible+=5;draw()},180)});
  feed.addEventListener('click',async e=>{const saveButton=e.target.closest('[data-save]');if(saveButton){let ids=saved();ids=ids.includes(saveButton.dataset.save)?ids.filter(id=>id!==saveButton.dataset.save):[...ids,saveButton.dataset.save];save(ids);draw();notify(ids.includes(saveButton.dataset.save)?'Notícia salva neste dispositivo.':'Notícia removida dos salvos.');return}const share=e.target.closest('[data-share]');if(!share)return;const post=posts.find(p=>p.slug===share.dataset.share),url=new URL(`post.html?slug=${encodeURIComponent(post.slug)}`,location.href).href;try{if(navigator.share)await navigator.share({title:post.title,text:post.excerpt,url});else{await navigator.clipboard.writeText(url);notify('Endereço da notícia copiado.')}}catch(error){if(error.name!=='AbortError')notify('Não foi possível compartilhar agora.')}});
  async function load(){drawCategories();feed.innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';try{posts=await APP.api('/api/posts?status=published');drawTrending();draw()}catch(error){feed.innerHTML='';ui.status.textContent='Não foi possível carregar as notícias agora. Tente novamente em instantes.'}}load();
})();
