(() => {
  const feed=document.querySelector('#post-feed'); if(!feed) return;
  const status=document.querySelector('#feed-status'), search=document.querySelector('#post-search'), filters=document.querySelector('#category-filters'), more=document.querySelector('#load-more');
  let posts=[], visible=5, category='Todas';
  const card=p=>`<article class="post-card reveal visible"><a class="post-cover" href="/blog/${APP.escape(p.slug)}"><img src="${APP.escape(p.cover_url||APP.fallbackImage)}" alt="${APP.escape(p.cover_alt||p.title)}" loading="lazy" onerror="this.src='${APP.fallbackImage}'"></a><div class="post-card-body"><div class="post-meta"><span>${APP.escape(p.category)}</span><time datetime="${APP.escape(p.published_at)}">${APP.formatDate(p.published_at)}</time></div><h2><a href="/blog/${APP.escape(p.slug)}">${APP.escape(p.title)}</a></h2><p>${APP.escape(p.excerpt)}</p><div class="post-card-foot"><span>${APP.readingTime(p.content)} min de leitura</span><a class="text-link" href="/blog/${APP.escape(p.slug)}">Ler notícia completa →</a></div></div></article>`;
  function draw(){const term=search.value.trim().toLocaleLowerCase('pt-BR');const list=posts.filter(p=>(category==='Todas'||p.category===category)&&(!term||`${p.title} ${p.excerpt} ${p.content}`.toLocaleLowerCase('pt-BR').includes(term)));feed.innerHTML=list.slice(0,visible).map(card).join('');feed.setAttribute('aria-busy','false');status.textContent=list.length?'': 'Nenhuma notícia encontrada. Tente outro termo ou categoria.';more.hidden=list.length<=visible;}
  function buttons(){filters.innerHTML=['Todas',...APP.categories].map(c=>`<button type="button" class="${c===category?'active':''}" data-category="${APP.escape(c)}">${APP.escape(c)}</button>`).join('');}
  filters.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;category=b.dataset.category;visible=5;buttons();draw()}); search.addEventListener('input',()=>{visible=5;draw()}); more.addEventListener('click',()=>{visible+=5;draw()});
  async function load(){buttons();feed.innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';if(!APP.configured){feed.innerHTML='';status.innerHTML='O feed será exibido assim que o Supabase for configurado. Consulte o README para conectar o banco.';return}const {data,error}=await APP.db.from('posts').select('*').eq('status','published').lte('published_at',new Date().toISOString()).order('featured',{ascending:false}).order('published_at',{ascending:false});if(error){feed.innerHTML='';status.textContent='Não foi possível carregar as notícias agora. Tente novamente em instantes.';return}posts=data||[];draw()} load();
})();
