const fs=require('fs');
const path=require('path');
const root=__dirname;
const dist=path.join(root,'dist');
fs.rmSync(dist,{recursive:true,force:true});
fs.mkdirSync(dist,{recursive:true});
for(const file of ['index.html','blog.html','post.html','styles.css','home-news.css','blog.css','post.css','admin.css','script.js','home-news.js','menu-extra.js','data.js','supabase.js','blog.js','post.js','admin.js'])fs.copyFileSync(path.join(root,file),path.join(dist,file));
fs.cpSync(path.join(root,'assets'),path.join(dist,'assets'),{recursive:true});
fs.cpSync(path.join(root,'admin'),path.join(dist,'admin'),{recursive:true});
fs.copyFileSync(path.join(root,'_redirects'),path.join(dist,'_redirects'));
console.log('Build estático criado em dist/');
