(async()=>{
  const article=document.querySelector('#article'),status=document.querySelector('#article-status');
  const slug=new URLSearchParams(location.search).get('slug')||decodeURIComponent(location.pathname.split('/').filter(Boolean).pop()||'');
  if(!APP.configured){status.textContent='O banco de notícias ainda não foi configurado.';return}
  const {data:p,error}=await APP.db.from('posts').select('*').eq('slug',slug).eq('status','published').lte('published_at',new Date().toISOString()).maybeSingle();
  if(error||!p){status.innerHTML='Notícia não encontrada ou indisponível. <a href="blog.html">Voltar ao blog</a>.';return}
  const canonical=new URL(`post.html?slug=${encodeURIComponent(p.slug)}`,location.href).href;
  document.title=`${p.seo_title||p.title} | Sanches Paiva`;document.querySelector('meta[name=description]').content=p.seo_description||p.excerpt;
  [['canonical','link','href'],['og:title','meta','content'],['og:description','meta','content'],['og:image','meta','content'],['og:url','meta','content']].forEach(([key,tag,attr])=>{let el=key==='canonical'?document.querySelector('link[rel=canonical]'):document.querySelector(`meta[property="${key}"]`);if(!el){el=document.createElement(tag);key==='canonical'?el.rel='canonical':el.setAttribute('property',key);document.head.append(el)}el[attr]=key==='canonical'||key==='og:url'?canonical:key==='og:title'?(p.seo_title||p.title):key==='og:description'?(p.seo_description||p.excerpt):(p.cover_url||APP.fallbackImage)});
  const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'NewsArticle',headline:p.title,description:p.excerpt,image:p.cover_url?[p.cover_url]:undefined,datePublished:p.published_at,dateModified:p.updated_at,author:{'@type':'Person',name:'Sanches Paiva Macedo'},mainEntityOfPage:canonical});document.head.append(schema);
  const gallery=Array.isArray(p.gallery)&&p.gallery.length?`<div class="article-gallery">${p.gallery.map(i=>`<img src="${APP.escape(i.url||i)}" alt="${APP.escape(i.alt||p.title)}" loading="lazy">`).join('')}</div>`:'';
  article.innerHTML=`<header class="article-head"><div class="wrap"><nav class="breadcrumb" aria-label="Navegação estrutural"><a href="index.html">Início</a><span>/</span><a href="blog.html">Notícias</a><span>/</span><span aria-current="page">${APP.escape(p.title)}</span></nav><p class="eyebrow">${APP.escape(p.category)}</p><h1>${APP.escape(p.title)}</h1><p class="article-lead">${APP.escape(p.excerpt)}</p><div class="article-meta"><time datetime="${APP.escape(p.published_at)}">${APP.formatDate(p.published_at)}</time><span>${p.reading_time||APP.readingTime(p.content)} min de leitura</span></div></div></header><div class="wrap article-shell"><img class="article-cover" src="${APP.escape(p.cover_url||APP.fallbackImage)}" alt="${APP.escape(p.cover_alt||p.title)}"><div class="article-content">${APP.renderMarkdown(p.content)}</div>${gallery}${p.source_url?'<p class="article-source">Referência editorial arquivada: publicação pública no perfil oficial.</p>':''}<a class="btn" href="blog.html">← Voltar ao blog</a></div>`;
  status.hidden=true;article.hidden=false;
  const {data:rels}=await APP.db.from('posts').select('title,slug,cover_url,cover_alt,category').eq('status','published').neq('id',p.id).eq('category',p.category).lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).limit(3);
  if(rels?.length){document.querySelector('#related').hidden=false;document.querySelector('#related-grid').innerHTML=rels.map(r=>`<article><img src="${APP.escape(r.cover_url||APP.fallbackImage)}" alt="${APP.escape(r.cover_alt||r.title)}" loading="lazy"><span>${APP.escape(r.category)}</span><h3><a href="post.html?slug=${encodeURIComponent(r.slug)}">${APP.escape(r.title)}</a></h3></article>`).join('')}
})();
