const fs=require('fs'),assert=require('assert'),cp=require('child_process');
const read=file=>fs.readFileSync(file,'utf8');
for(const file of ['script.js','home-news.js','supabase.js','blog.js','post.js','admin.js'])cp.execFileSync(process.execPath,['--check',file],{stdio:'inherit'});
const css=read('styles.css'),sql=read('supabase/migration.sql'),admin=read('admin.js'),post=read('post.js'),blog=read('blog.js');
for(const token of ['position:fixed','width:min(320px,calc(100vw - 24px))','max-height:calc(100dvh - 100px)','z-index:1000','overflow-y:auto'])assert(css.includes(token),`Menu mobile sem ${token}`);
assert(!css.includes('min-height:100dvh'),'O menu mobile não deve ocupar a altura inteira');
assert(css.includes('@media(max-width:390px)'),'Breakpoint de 390px ausente');
assert(admin.includes("signInWithPassword")&&admin.includes("rpc('is_admin')"),'Autenticação administrativa ausente');
assert(admin.includes("code==='23505'")&&admin.includes('validImage'),'Validação de slug/upload ausente');
assert(sql.includes('enable row level security')&&sql.includes('public reads published posts'),'RLS pública ausente');
assert(sql.includes('admins insert posts')&&sql.includes('admins delete posts'),'RLS administrativa ausente');
assert(post.includes("eq('slug',slug)")&&post.includes('NewsArticle'),'Rota dinâmica ou SEO ausente');
assert(blog.includes("eq('status','published')")&&blog.includes('data-share')&&blog.includes('data-save'),'Feed público incompleto');
assert(sql.includes('record_post_view')&&sql.includes('post_views'),'Contador seguro de visualizações ausente');
assert(read('supabase.js').includes('textContent=String(value)'),'Escape de conteúdo ausente');
console.log('Todos os testes estruturais passaram.');
