const fs=require('fs'),assert=require('assert'),cp=require('child_process');
const read=file=>fs.readFileSync(file,'utf8');
for(const file of ['server.js','script.js','home-news.js','supabase.js','editorial-posts.js','blog.js','post.js','admin.js'])cp.execFileSync(process.execPath,['--check',file],{stdio:'inherit'});
const css=read('styles.css'),server=read('server.js'),admin=read('admin.js'),post=read('post.js'),blog=read('blog.js'),schema=read('database/schema.sql');
for(const token of ['position:fixed','width:min(320px,calc(100vw - 24px))','max-height:calc(100dvh - 100px)','z-index:1000','overflow-y:auto'])assert(css.includes(token),`Menu mobile sem ${token}`);
assert(server.includes('HttpOnly; SameSite=Strict')&&server.includes('bcrypt.compare'),'Autenticação segura ausente');
assert(server.includes('require.main===module')&&server.includes('module.exports=app'),'Inicialização serverless ausente');
assert(server.includes("app.post('/api/posts'")&&server.includes("app.put('/api/posts/:id'")&&server.includes("app.delete('/api/posts/:id'"),'CRUD administrativo incompleto');
assert(server.includes("app.post('/api/uploads'")&&server.includes('8*1024*1024'),'Upload protegido incompleto');
assert(admin.includes("APP.api('/api/auth/login'")&&admin.includes("APP.api('/api/uploads'"),'Painel não conectado à API');
assert(post.includes('?public=1')&&post.includes('NewsArticle'),'Post público ou SEO ausente');
assert(blog.includes("APP.api('/api/posts?status=published')")&&blog.includes('data-share')&&blog.includes('data-save'),'Feed público incompleto');
assert(blog.includes('window.EDITORIAL_POSTS')&&read('blog.html').includes('editorial-posts.js'),'Fallback local do feed ausente');
assert(schema.includes('create table if not exists posts')&&schema.includes('create table if not exists admins'),'Schema PostgreSQL incompleto');
assert(read('supabase.js').includes('textContent=String(value)'),'Escape de conteúdo ausente');
const editorial=require('./editorial-posts.js'),eventSlug='ocidental-gastro-movimenta-comercio-cultura-e-turismo',event=editorial[eventSlug],home=read('index.html');
assert(event&&event.layout==='ocidental-gastro'&&event.images.length===20,'Conteúdo editorial do Ocidental Gastrô incompleto');
assert(home.includes(`./post.html?slug=${eventSlug}`)&&home.includes('Conheça o evento'),'Card do Ocidental Gastrô sem destino ou chamada');
for(const image of event.images)assert(fs.existsSync(`.${image.url}`),`Imagem editorial ausente: ${image.url}`);
const employmentSlug='3-feirao-do-emprego-supera-2300-atendimentos',employment=editorial[employmentSlug];
assert(employment&&employment.layout==='feirao-emprego'&&employment.images.length===9,'Conteúdo editorial do Feirão do Emprego incompleto');
assert(employment.published_at==='2023-12-03'&&employment.source_label==='Fonte das informações: Prefeitura Municipal de Cidade Ocidental.','Data ou fonte do Feirão incorreta');
assert(home.includes(`./post.html?slug=${employmentSlug}`)&&home.includes('Conheça essa iniciativa'),'Card do Feirão sem destino ou chamada');
assert(!home.includes('Desenvolvimento econômico é criar caminhos para quem trabalha e empreende.'),'Card redundante de Emprego e renda ainda está na página inicial');
for(const image of employment.images)assert(fs.existsSync(`.${image.url}`),`Imagem do Feirão ausente: ${image.url}`);
const religiousSlug='turismo-religioso-valoriza-vocacao-e-identidade-cultural';
const religious=editorial[religiousSlug];
assert(religious?.status==='published'&&religious.layout==='turismo-religioso'&&religious.images.length===14,'Matéria de Turismo religioso incompleta');
assert(religious.video?.url&&fs.existsSync(`.${religious.video.url}`)&&fs.existsSync(`.${religious.video.poster}`),'Vídeo ou poster do Turismo religioso ausente');
assert(religious.reading_time>1&&read('script.js').includes(`'${religiousSlug}'`),'Tempo de leitura ou card de Turismo religioso incorreto');
for(const image of religious.images)assert(fs.existsSync(`.${image.url}`),`Imagem do Turismo religioso ausente: ${image.url}`);
assert(![read('post.js'),read('post.css'),read('employment-post.css'),read('religious-post.css'),read('editorial-posts.js')].join('').includes('/workspace/scratch'),'Caminho temporário encontrado');
console.log('Todos os testes estruturais passaram.');
